### ISSUE TITLE
navbar 2 some new development 

### ISSUE THREAD

**Issue by HarshRajbhar** [rpsoftech/AngularComponents#11]

**Comment by keyurboss** [comment]
Use Span Instead Of Img tag
![image](https://user-images.githubusercontent.com/51239095/205012410-975257e2-cb3a-4b80-96a1-ca54cae98d5e.png)
Use This
![image](https://user-images.githubusercontent.com/51239095/205012567-30fbd290-7b7c-47c1-9966-287150d5b5a1.png)

**Comment by keyurboss** [comment]
Change Interface from 
![image](https://user-images.githubusercontent.com/51239095/205012663-a27f97ac-3eb5-40c6-ae89-2af6fd743979.png)
Something Like This
![image](https://user-images.githubusercontent.com/51239095/205012731-a5c0df98-29ae-48b1-99a7-710cfdedc715.png)
